name: Tests

on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
      - main

concurrency:
  group: running-tests
  cancel-in-progress: true

jobs:
  build-test:
    name: Build test
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          cp moodmeter/Local.xcconfig.sample moodmeter/Local.xcconfig

          xcodebuild -project moodmeter.xcodeproj \
          -scheme moodmeter \
          -sdk iphonesimulator \
          -derivedDataPath './output' \
          build \
          CODE_SIGNING_ALLOWED=NO

  swiftlint:
    name: Swiftlint
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - run: swiftlint --strict --config .swiftlint.ci.yml --config .swiftlint.yml

  editorconfig-check:
    name: Editorconfig check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: editorconfig-checker/action-editorconfig-checker@main
      - run: editorconfig-checker

  tests-succeeded:
    name: Tests Succeeded
    needs:
      - build-test
      - swiftlint
      - editorconfig-check

    runs-on: ubuntu-latest
    steps:
      - name: All clear
        run: exit 0
